title: Alison's Projects
description: <p align="center">....explaining some of my GitHub Projects</p>
show_downloads: 
google_analytics:
theme: jekyll-theme-tactile
markdown: kramdown
kramdown:
  input: GFM
