title: Explaining my github projects
description: This is a breakdown of the different repository,for a better understanding
show_downloads: 
google_analytics:
theme: jekyll-theme-architect

markdown: kramdown
kramdown:
  input: GFM
