title: Hi, My name is Alison...kindly allow me to explain my github projects
description: The repos are further broken down 
show_downloads: 
google_analytics:
theme: jekyll-theme-architect

markdown: kramdown
kramdown:
  input: GFM
